config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "dashboard#index"
  get :dashboard, to: "dashboard#index", as: 'dashboard'
  resources :nominees
  devise_for :accounts

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :nominees, class_name: 'NomineeRecord', foreign_key: :nominated_by_id
  # has_many :nominated_list, class_name: 'NomineeRecord', foreign_key: :nominee_id       

  # has_many :nominees_nominee_records, class_name: 'NomineeRecord', foreign_key: :nominated_by_id
  # has_many :my_nominees, through: :nominees_nominee_records, source: :nominated_list, class_name: 'Account'
  # has_many :nominated_nominee_records, class_name: 'NomineeRecord', foreign_key: :nominee_id
  # has_many :nominated_list, through: :nominated_nominee_records, source: :nominee, class_name: 'Account'

  has_many :nominee_records
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/nominee_record.rb
class NomineeRecord < ApplicationRecord
  # belongs_to :nominee, class_name: "Account", foreign_key: :nominated_by_id
  # belongs_to :nominated_list, class_name: "Account", foreign_key: :nominee_id

  belongs_to :account
  belongs_to :nominee, class_name: "Account", foreign_key: :nominee_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_account!
  
  def index
    @nominated_list = NomineeRecord.where(nominee_id: current_account.id)
  end
end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController
  before_action :authenticate_account!
  
  def new
    @nominee = NomineeRecord.new
  end

  def create
    @nominee = NomineeRecord.create(nominee_params)
    if @nominee.persisted?
      flash[:notice] = "Nominee added successfully"
      redirect_to dashboard_path
    else
      flash[:alert] = @nominee.errors.full_messages.join(", ")
      redirect_back(fallback_location: new_nominee_path)
    end
  end

  private

    def nominee_params
      params.require(:nominee_record).permit(:nominee_id, :account_id, :relationship, :weightage)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/views/dashboard/index.html.erb
<div class="row">

<div class="col text-center card mr-4">
  <h1>My account</h1>
   <%= image_tag ('avatar.png'), class: "img-profile rounded-circle"%>
  <div class="card-body">
    <h5 class="card-title"><%= current_account.first_name%></h5>
    <p class="card-text">$<%= current_account.balance%></p>
  </div>
</div>

  <div class="col text-center card mr-4">
    <h1>My Nominees <%=link_to "Add", new_nominee_path, class:"btn btn-primary"%></h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">First name</th>
          <th scope="col">Relation</th>
          <th scope="col">Weightage</th>
        </tr>
      </thead>
      <tbody>
        <%current_account.nominee_records.each_with_index do |nominee_record, i|%>
        <tr>
          <td><%= nominee_record.nominee.first_name%></td>
          <td><%= nominee_record.relationship%></td>
          <td><%=nominee_record.weightage%>%</td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>

  <div class="col text-center card">
    <h1>Nominated List</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">First name</th>
        </tr>
      </thead>
      <tbody>
        <%@nominated_list.each_with_index do |nominated_by, i|%>
        <tr>
          <td><%= nominated_by.account.first_name%></td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BacancyAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'layouts/shared/navbar' %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <a class="navbar-brand" href="/">Bank Assignment</a>
  <%if current_account.present? %>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
        <%= button_to(destroy_account_session_path, {class: "nav-link btn btn-primary", method: :delete}) do %>
          <span class="text-white">Logout</span>
        <% end %>
        </li>
      </ul>
    </div>
  <%end%>
</nav>

app/views/nominees/_form.html.erb
<div class="" data-controller="validation">                  
<%= form_with model: nominee, url: nominees_path, class: "", local: true  do |f| %>
    <div class="form-group row">
        <%= f.hidden_field :account_id, value: current_account.id%>
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label for="colFormLabel" class="col-form-label">Relation Ship</label><span class="text-danger">*</span>
          <%= f.text_field :relationship, class: 'form-control', placeholder: "wine master name", required: true %>
        </div>
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label for="colFormLabel" class="col-form-label">Weightage</label><span class="text-danger">*</span>
          <%= f.select :weightage,
                  options_for_select([10,20,30,40,50,60,70,80,90,100], f.object.weightage), {include_blank: "Select weightage"},
                  {class: "form-control mr-2", required: true}%>
          </div>
        <div class="col-sm-6 mb-3 mb-sm-0">
          <label for="colFormLabel" class="col-form-label">Select Nominee</label><span class="text-danger">*</span>
          <%= f.select :nominee_id,
                  options_from_collection_for_select(Account.where.not(id: current_account.id), "id", "first_name", f.object.nominee_id), {include_blank: "Select nominee"},
                  {class: "form-control mr-2", required: true} %>
        </div> 
    </div>
  
    <%= f.submit "Add", class: "btn btn-primary btn-user float-right mt-2"%>
  <%end%>
</div>

app/views/nominees/new.html.erb
<h1>Add Nominee</h1>
<div class="card" data-controller="base">
  <div class="card-body" id="wine_create">

     <%= render partial: "nominees/form", locals: { nominee: @nominee} %>
  </div>
</div>